---

- hosts: container-servers

  tasks:
    - name: Setup Networking
      template: owner=root group=root mode=644
                  src=/etc/ansible/templates/interfaces
                  dest=/etc/network/interfaces
